### ISSUE TITLE
To-Do feature list

### ISSUE THREAD

**Issue by dlukens** [dlukens/PyRocket#1]
- [ ] Generate stars / clouds
- [ ] GUI
- [ ] Sizing / Control
- [ ] VFX / SFX
- [ ] Landing platform. Dynamic?
- [ ] Edge cases / death
- [ ] Sprites / Textures
- [ ] Refactoring
- [ ] Add drag and enhance gravity calculation
